"use client";

import Link from "next/link";
import { Award, Compass, Gift, Check, ArrowRight, Shield, Sparkles } from "lucide-react";

export default function AmbassadorPage() {
  return (
    <div className="bg-forge-navy py-12 sm:py-20">
      {/* Hero Banner */}
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="text-center space-y-6 max-w-3xl mx-auto">
          <div className="inline-flex items-center gap-1.5 rounded-full bg-forge-orange/10 border border-forge-orange/30 px-3.5 py-1 text-xs font-semibold uppercase tracking-wider text-forge-orange">
            <Sparkles className="h-3.5 w-3.5 animate-pulse" />
            <span>Community Builder Program</span>
          </div>
          <h1 className="font-display text-4xl font-black uppercase tracking-tight sm:text-6xl text-forge-white">
            Forge <span className="text-forge-orange">Ambassador</span> <br />
            Program
          </h1>
          <p className="text-lg text-forge-steel leading-relaxed">
            Help grow the blue-collar job platform in your local community. Recruit skilled tradespeople and customers, and earn a generous recurring commission.
          </p>
          <div className="pt-4">
            <Link
              href="/ambassador/register"
              className="group inline-flex items-center gap-3 rounded-full bg-forge-orange px-8 py-4 text-base font-bold text-forge-white shadow-xl shadow-forge-orange/20 hover:bg-forge-orange-dark hover:scale-105 active:scale-95 transition-all"
            >
              <span>Apply to be an Ambassador</span>
              <ArrowRight className="h-5 w-5 transform group-hover:translate-x-1 transition-transform" />
            </Link>
          </div>
        </div>
      </div>

      {/* Perks Grid */}
      <div className="mx-auto max-w-7xl px-4 mt-24 sm:px-6 lg:px-8">
        <div className="text-center space-y-4 mb-16">
          <h2 className="font-display text-3xl font-extrabold uppercase tracking-tight text-forge-white">
            What You Earn
          </h2>
          <p className="max-w-xl mx-auto text-sm text-forge-steel">
            Earn cash, exclusive swag, and build high-value connections by representing Forge locally.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="bg-forge-navy-light/40 border border-forge-steel/15 p-8 rounded-2xl space-y-4 hover:border-forge-orange/30 transition-all">
            <div className="h-10 w-10 rounded-lg bg-forge-orange/10 flex items-center justify-center text-forge-orange">
              <Gift className="h-5 w-5" />
            </div>
            <h3 className="font-display text-xl font-bold text-forge-white">10% Recurring Commission</h3>
            <p className="text-sm text-forge-steel leading-relaxed">
              Earn 10% of the platform transaction matching fees generated by any customer or professional you refer, paid monthly for the first 6 months.
            </p>
          </div>

          <div className="bg-forge-navy-light/40 border border-forge-steel/15 p-8 rounded-2xl space-y-4 hover:border-forge-orange/30 transition-all">
            <div className="h-10 w-10 rounded-lg bg-forge-orange/10 flex items-center justify-center text-forge-orange">
              <Award className="h-5 w-5" />
            </div>
            <h3 className="font-display text-xl font-bold text-forge-white">Exclusive Ambassador Swag</h3>
            <p className="text-sm text-forge-steel leading-relaxed">
              Get premium chiseled Forge gear: heavy-duty tool belts, branded car decals, canvas hoodies, and promotional trade brochures to hand out.
            </p>
          </div>

          <div className="bg-forge-navy-light/40 border border-forge-steel/15 p-8 rounded-2xl space-y-4 hover:border-forge-orange/30 transition-all">
            <div className="h-10 w-10 rounded-lg bg-forge-orange/10 flex items-center justify-center text-forge-orange">
              <Compass className="h-5 w-5" />
            </div>
            <h3 className="font-display text-xl font-bold text-forge-white">Local Lead Opportunities</h3>
            <p className="text-sm text-forge-steel leading-relaxed">
              Host regional meetups, onboarding events, and act as the principal voice of Forge in your area, positioning you as a key community organizer.
            </p>
          </div>
        </div>
      </div>

      {/* Eligible stepper */}
      <div className="bg-forge-navy-light/20 border-y border-forge-navy-light/60 py-24 mt-24">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="text-center space-y-4 mb-20">
            <h2 className="font-display text-3xl font-extrabold uppercase tracking-tight text-forge-white">
              Ambassador Stepper
            </h2>
            <p className="max-w-xl mx-auto text-sm text-forge-steel">
              Our onboarding program is designed to set you up for absolute success.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            <div className="space-y-4">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-forge-navy-light border border-forge-steel/30 text-forge-orange font-display font-black">
                1
              </div>
              <h3 className="text-lg font-bold text-forge-white">Apply Online</h3>
              <p className="text-xs text-forge-steel leading-relaxed">
                Fill the Ambassador form. Explain your background, local connections, and why you want to represent Forge.
              </p>
            </div>

            <div className="space-y-4">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-forge-navy-light border border-forge-steel/30 text-forge-orange font-display font-black">
                2
              </div>
              <h3 className="text-lg font-bold text-forge-white">Brief Interview</h3>
              <p className="text-xs text-forge-steel leading-relaxed">
                Hop on a short 15-minute alignment call with our Community Director to align on local growth strategies.
              </p>
            </div>

            <div className="space-y-4">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-forge-navy-light border border-forge-steel/30 text-forge-orange font-display font-black">
                3
              </div>
              <h3 className="text-lg font-bold text-forge-white">Onboard & Swag</h3>
              <p className="text-xs text-forge-steel leading-relaxed">
                Gain access to your custom referral dashboard link, print resources, and receive your welcome package.
              </p>
            </div>

            <div className="space-y-4">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-forge-navy-light border border-forge-steel/30 text-forge-orange font-display font-black">
                4
              </div>
              <h3 className="text-lg font-bold text-forge-white">Launch & Earn</h3>
              <p className="text-xs text-forge-steel leading-relaxed">
                Invite contractors and clients, host informational panels, track your dashboard signups, and collect payouts.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Verification / Requirements */}
      <div className="mx-auto max-w-4xl px-4 mt-24">
        <div className="bg-forge-navy-light/30 border border-forge-steel/15 rounded-3xl p-8 sm:p-10 space-y-6">
          <div className="flex items-center gap-3">
            <Shield className="h-6 w-6 text-forge-orange shrink-0" />
            <h3 className="font-display text-xl font-bold text-forge-white uppercase tracking-wider">
              Who We Are Looking For
            </h3>
          </div>
          <p className="text-sm text-forge-steel leading-relaxed">
            While anyone is welcome to apply, the program is heavily suited for:
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="flex items-center gap-3">
              <div className="h-5 w-5 rounded-full bg-forge-orange/15 flex items-center justify-center text-forge-orange shrink-0">
                <Check className="h-3 w-3" />
              </div>
              <span className="text-xs text-forge-white font-medium">Local trade association organizers</span>
            </div>
            <div className="flex items-center gap-3">
              <div className="h-5 w-5 rounded-full bg-forge-orange/15 flex items-center justify-center text-forge-orange shrink-0">
                <Check className="h-3 w-3" />
              </div>
              <span className="text-xs text-forge-white font-medium">Active vocational trade students</span>
            </div>
            <div className="flex items-center gap-3">
              <div className="h-5 w-5 rounded-full bg-forge-orange/15 flex items-center justify-center text-forge-orange shrink-0">
                <Check className="h-3 w-3" />
              </div>
              <span className="text-xs text-forge-white font-medium">Real estate and property managers</span>
            </div>
            <div className="flex items-center gap-3">
              <div className="h-5 w-5 rounded-full bg-forge-orange/15 flex items-center justify-center text-forge-orange shrink-0">
                <Check className="h-3 w-3" />
              </div>
              <span className="text-xs text-forge-white font-medium">Enthusiastic neighborhood community heads</span>
            </div>
          </div>
          <div className="pt-6 border-t border-forge-navy-light/60 text-center">
            <Link
              href="/ambassador/register"
              className="inline-flex items-center justify-center gap-2 rounded-full bg-forge-orange px-8 py-3.5 text-sm font-bold text-forge-white hover:bg-forge-orange-dark transition-all"
            >
              <span>Submit Ambassador Application</span>
              <ArrowRight className="h-4 w-4" />
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
